repos:
  - repo: local
    hooks:
      - id: cargo-check
        name: cargo check
        entry: cargo check --all-targets
        language: system
        pass_filenames: false
        types_or: [rust, toml]
        files: \.(rs|toml)$|Cargo\.lock$|rust-toolchain\.toml$

      - id: cargo-fmt
        name: cargo fmt
        entry: cargo +nightly fmt --all -- --check
        language: system
        pass_filenames: false
        types_or: [rust, toml]
        files: \.(rs|toml)$|Cargo\.lock$|rust-toolchain\.toml$

      - id: cargo-clippy
        name: cargo clippy
        entry: cargo clippy --all-targets --no-deps -- -D warnings
        language: system
        pass_filenames: false
        types_or: [rust, toml]
        files: \.(rs|toml)$|Cargo\.lock$|rust-toolchain\.toml$

      - id: cargo-doc
        name: cargo doc
        entry: env RUSTDOCFLAGS="-D warnings" cargo +nightly doc --no-deps --document-private-items
        language: system
        pass_filenames: false
        types_or: [rust, toml]
        files: \.(rs|toml)$|Cargo\.lock$|rust-toolchain\.toml$

      - id: conventional-commit
        name: conventional commit message
        entry: scripts/check-conventional-commit.sh
        language: script
        stages: [commit-msg]
        always_run: true
